
const D=window.WIKI_DATA||{items:[],tags:[],maps:[],admin_commands:[],admin_command_details:[],explain_cards:[]};
const sections=[...document.querySelectorAll('.section')],nav=[...document.querySelectorAll('.nav button[data-section]')];
function show(id){sections.forEach(s=>s.classList.toggle('active',s.id===id));nav.forEach(b=>b.classList.toggle('active',b.dataset.section===id));if(!location.hash.startsWith('#command-'))location.hash=id;window.scrollTo({top:0,behavior:'smooth'});document.querySelector('.sidebar')?.classList.remove('drawer')}
nav.forEach(b=>b.onclick=()=>show(b.dataset.section));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>show(b.dataset.goto));
const labelMap=new Map((D.tags||[]).map(t=>[t.key,t.label]));
function itemCard(x){const tags=(x.tags||[]).filter(t=>t.kind!=='meta'&&t.key!=='detail:Admin / Private weapon').slice(0,2);const admin=x.admin_private?`<span class="tag admin-tag">ADMIN / PRIVATE</span>`:'';return `<article class="card clickable item-card ${x.admin_private?'admin-item':''}" data-id="${x.id}"><div class="tags"><span class="tag">#${String(x.order).padStart(3,'0')}</span>${admin}${tags.map(t=>`<span class="tag ${t.kind==='detail'?'green':'blue'}">${t.label}</span>`).join('')}</div><h3>${x.name}</h3><p>${x.detail}</p>${x.admin_private?`<p class="admin-note">Только Private Server</p>`:''}</article>`}
function bindItems(root=document){root.querySelectorAll('.item-card').forEach(el=>el.onclick=()=>openItem(D.items.find(x=>x.id===el.dataset.id)))}
function openItem(x){if(!x)return;document.getElementById('itemModalContent').innerHTML=`${x.admin_private?'<div class="admin-banner">ADMIN / PRIVATE SERVER WEAPON</div>':''}<h2>${x.name}</h2><div class="tags" style="margin-bottom:12px">${(x.tags||[]).map(t=>`<span class="tag ${t.key==='detail:Admin / Private weapon'?'admin-tag':t.kind==='detail'?'green':t.kind==='meta'?'gray':'blue'}">${t.label}</span>`).join('')}</div><div class="detail"><b>Порядок</b><span>#${x.order} из ${D.items.length}</span></div><div class="detail"><b>Категория</b><span>${x.category}</span></div><div class="detail"><b>Подтип</b><span>${x.detail}</span></div>${x.admin_private?`<div class="detail"><b>Доступность</b><span>${x.availability_note}</span></div>`:''}`;openModal('itemModal')}
function openModal(id){document.getElementById(id)?.classList.add('open')}function closeModal(id){document.getElementById(id)?.classList.remove('open')}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});
const firearms=D.items.filter(x=>x.category==='Firearm / launcher'),melee=D.items.filter(x=>x.category==='Melee'||x.category==='Shield'),attach=D.items.filter(x=>x.category==='Attachment'),other=D.items.filter(x=>!['Firearm / launcher','Melee','Shield','Attachment'].includes(x.category));
function fill(id,arr){const el=document.getElementById(id);if(!el)return;el.innerHTML=arr.map(itemCard).join('');bindItems(el)}
fill('weaponGrid',firearms);fill('meleeGrid',melee);fill('attachmentGrid',attach);fill('otherGrid',other);
const fullTable=document.getElementById('fullTable');if(fullTable)fullTable.innerHTML=`<table class="list-table"><thead><tr><th>#</th><th>Название</th><th>Категория</th><th>Подтип</th></tr></thead><tbody>${D.items.map(x=>`<tr><td>${x.order}</td><td>${x.name}</td><td>${x.category}</td><td>${x.detail}</td></tr>`).join('')}</tbody></table>`;

// Simple V10-style tag filtering, with multi-select and visible current selection.
const categoryTags=(D.tags||[]).filter(t=>t.kind==='category'),detailTags=(D.tags||[]).filter(t=>t.kind==='detail');
const selected=new Set();
function loadTagUrl(){new URLSearchParams(location.search).getAll('tag').forEach(k=>{if(labelMap.has(k))selected.add(k)})}
function saveTagUrl(){const qs=new URLSearchParams(location.search);qs.delete('tag');[...selected].sort().forEach(k=>qs.append('tag',k));history.replaceState(null,'',location.pathname+(qs.toString()?`?${qs}`:'')+location.hash)}
function selectedByKind(){const r={category:[],detail:[]};selected.forEach(k=>{if(k.startsWith('category:'))r.category.push(k);else if(k.startsWith('detail:'))r.detail.push(k)});return r}
function itemHas(x,k){return(x.tags||[]).some(t=>t.key===k)}
function filtered(){const g=selectedByKind();let arr=D.items.slice();if(g.category.length)arr=arr.filter(x=>g.category.some(k=>itemHas(x,k)));if(g.detail.length)arr=arr.filter(x=>g.detail.some(k=>itemHas(x,k)));return arr}
function toggleTag(k){if(selected.has(k))selected.delete(k);else selected.add(k);saveTagUrl();renderFilters()}
function clearTags(){selected.clear();saveTagUrl();renderFilters()}
function filterButton(t){return `<button class="filter-btn ${selected.has(t.key)?'selected':''}" data-tagkey="${t.key}">${t.label} <span class="count">${t.count}</span></button>`}
function renderFilters(){
 const cats=document.getElementById('categoryFilters'),details=document.getElementById('detailFilters'),cloud=document.getElementById('allTagCloud');
 if(cats)cats.innerHTML=`<button class="filter-btn ${selected.size===0?'selected':''}" data-clearall="1">Все</button>`+categoryTags.map(filterButton).join('');
 const g=selectedByKind();let visibleDetails=detailTags;if(g.category.length){const related=new Set();D.items.filter(x=>g.category.some(k=>itemHas(x,k))).forEach(x=>(x.tags||[]).filter(t=>t.kind==='detail').forEach(t=>related.add(t.key)));visibleDetails=detailTags.filter(t=>related.has(t.key));}
 if(details)details.innerHTML=visibleDetails.map(filterButton).join('');
 if(cloud)cloud.innerHTML=[...categoryTags,...detailTags].map(t=>`<button class="tag-btn ${selected.has(t.key)?'selected':''}" data-tagkey="${t.key}">${t.label} <span>${t.count}</span></button>`).join('');
 document.querySelectorAll('[data-tagkey]').forEach(b=>b.onclick=()=>toggleTag(b.dataset.tagkey));document.querySelectorAll('[data-clearall]').forEach(b=>b.onclick=clearTags);
 const arr=filtered(),grid=document.getElementById('itemGrid'),tagResults=document.getElementById('tagResults');if(grid){grid.innerHTML=arr.map(itemCard).join('');bindItems(grid)}if(tagResults){tagResults.innerHTML=arr.map(itemCard).join('');bindItems(tagResults)}
 const count=document.getElementById('itemCount');if(count)count.textContent=arr.length;const trc=document.getElementById('tagResultCount');if(trc)trc.textContent=`${arr.length} шт.`;
 const selectedLabels=[...selected].map(k=>labelMap.get(k)||k);const summary=document.getElementById('quickFilterSummary');if(summary)summary.innerHTML=selectedLabels.length?`<span class="muted">Выбрано:</span>`+ [...selected].map(k=>`<button class="selected-chip" data-remove-tag="${k}">${labelMap.get(k)||k}<b>×</b></button>`).join(''):`<span class="muted">Фильтр: Все items</span>`;
 document.querySelectorAll('[data-remove-tag]').forEach(b=>b.onclick=()=>{selected.delete(b.dataset.removeTag);saveTagUrl();renderFilters()});
 const st=document.getElementById('selectedTagsText');if(st)st.textContent=selectedLabels.length?selectedLabels.join(' + '):'ничего — показываются все items';const badge=document.getElementById('tagFilterBadge');if(badge){badge.textContent=selected.size;badge.hidden=selected.size===0}
}
loadTagUrl();document.getElementById('clearQuickFilters').onclick=clearTags;document.getElementById('clearTagsPage').onclick=clearTags;renderFilters();

// Admin commands and detailed mini-pages.
const helpMap=new Map((D.admin_command_details||[]).map(x=>[x.name,x]));
function commandCard(name){const h=helpMap.get(name)||{short:'Admin command.',verified:'partial'};return `<div class="admin-command"><div class="admin-command-top"><code>${name}</code><span class="verify-badge ${h.verified}">${h.verified==='verified'?'описание подтверждено':'частично подтверждено'}</span></div><p>${h.short||''}</p><div class="command-actions"><button class="more-command" data-command="${name}">Подробнее</button><button class="copy-command" data-copy="${name}">Копировать</button></div></div>`}
const adminGrid=document.getElementById('adminGrid');if(adminGrid)adminGrid.innerHTML=(D.admin_command_groups||[]).map(g=>`<section class="admin-group"><div class="admin-group-head"><h3>${g.title}</h3><span>${g.commands.length}</span></div><div class="admin-command-list">${g.commands.map(commandCard).join('')}</div></section>`).join('');
function openCommand(name,push=true){const h=helpMap.get(name);if(!h)return;const steps=(h.steps||[]).map(s=>`<div class="command-step">${s}</div>`).join('');const input=h.input?`<div class="detail"><b>Что вводить</b><span>${h.input}</span></div>`:'';const ex=h.example?`<div class="callout"><b>Пример:</b> ${h.example}</div>`:'';const note=h.note?`<div class="callout"><b>Примечание:</b> ${linkify(h.note)}</div>`:'';document.getElementById('commandModalContent').innerHTML=`<div class="tags"><span class="tag">${h.group}</span><span class="verify-badge ${h.verified}">${h.verified==='verified'?'подтверждено источниками':'частично подтверждено'}</span></div><h2>${h.name}</h2><p class="lead" style="font-size:16px">${h.what}</p>${input}<h3>Как использовать</h3><div class="command-steps">${steps}</div>${ex}${note}`;openModal('commandModal');if(push)history.replaceState(null,'',location.pathname+location.search+`#command-${encodeURIComponent(name)}`)}
function linkify(s){return s.replace(/https:\/\/[^\s<]+/g,u=>`<a href="${u}" target="_blank" rel="noopener">${u}</a>`)}
document.querySelectorAll('.more-command').forEach(b=>b.onclick=()=>openCommand(b.dataset.command));document.querySelectorAll('.copy-command').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Скопировано';setTimeout(()=>b.textContent='Копировать',1000)}catch{}});
const ac=document.getElementById('adminCount');if(ac)ac.textContent=(D.admin_commands||[]).length;

// Maps with external screenshots and honest image labels.
const mapsGrid=document.getElementById('mapsGrid');if(mapsGrid)mapsGrid.innerHTML=(D.maps||[]).map(m=>`<article class="card"><div class="map-cover"><img src="${m.image}" alt="${m.name}" onerror="this.parentElement.classList.add('failed');this.classList.add('error')"><div class="map-image-fallback">Изображение не загрузилось</div></div><div class="tags"><span class="tag blue">${m.status}</span></div><h3>${m.name}</h3><p>${m.desc}</p><div class="detail"><b>Admin name</b><span>${m.admin_name}</span></div><div class="image-note">${m.image_note}</div></article>`).join('');
const ex=document.getElementById('explainGrid');if(ex)ex.innerHTML=(D.explain_cards||[]).map(x=>`<article class="card"><h3>${x.title}</h3><p>${x.text}</p></article>`).join('');const sl=document.getElementById('sourceLinks');if(sl)sl.innerHTML=(D.sources||[]).map(s=>`<a href="${s.url}" target="_blank" rel="noopener">↗ ${s.label}</a>`).join('');

// Search
const searchInputs=[document.getElementById('search'),document.getElementById('searchMobile')].filter(Boolean);function doSearch(q){q=q.trim().toLowerCase();const panel=document.getElementById('searchPanel'),box=document.getElementById('searchResults');if(!q){panel.classList.remove('active');return}const items=D.items.filter(x=>(`${x.name} ${x.category} ${x.detail}`).toLowerCase().includes(q));const cmds=(D.admin_command_details||[]).filter(x=>(`${x.name} ${x.short} ${x.what}`).toLowerCase().includes(q));panel.classList.add('active');show('home');box.innerHTML=items.map(itemCard).join('')+cmds.map(x=>`<article class="card clickable command-search" data-command="${x.name}"><span class="tag">Admin Command</span><h3>${x.name}</h3><p>${x.short}</p></article>`).join('')||'<div class="notice">Ничего не найдено.</div>';bindItems(box);box.querySelectorAll('.command-search').forEach(x=>x.onclick=()=>openCommand(x.dataset.command))}searchInputs.forEach(i=>i.oninput=e=>doSearch(e.target.value));

document.getElementById('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('drawer');document.getElementById('closeDrawer').onclick=()=>document.querySelector('.sidebar').classList.remove('drawer');
// Initial route; support direct command links.
if(location.hash.startsWith('#command-')){show('admin');openCommand(decodeURIComponent(location.hash.slice(9)),false)}else{const id=location.hash.slice(1);if(id&&document.getElementById(id))show(id);else if(selected.size)show('items');else show('home')}
